"""changed table m2m v.2

Revision ID: 364c527b5f83
Revises: effb5c0d3cb0
Create Date: 2023-09-10 16:15:54.212726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364c527b5f83'
down_revision: Union[str, None] = 'effb5c0d3cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
