"""final upgrade

Revision ID: 69db5c8e0355
Revises: 364c527b5f83
Create Date: 2023-09-10 21:00:07.656924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69db5c8e0355'
down_revision: Union[str, None] = '364c527b5f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_contacts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_contacts', 'contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_contacts_user_id_fkey', 'users_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'users_contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_contacts', type_='foreignkey')
    op.create_foreign_key('users_contacts_user_id_fkey', 'users_contacts', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.alter_column('users_contacts', 'contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_contacts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
